### ISSUE TITLE
client for gigy-example in springboot

### ISSUE THREAD

**Issue by anotherrohit** [gigsterous/gigy-example#14]
I was able to run the resource server and authorizationserver for gigy/people and get  access token from oath/token. However i would like to register the gigy/people with a different Authorization server (eg github authorizationserver. I registered the http://localhost:8000/gigy/people to obtain a client secret etc. However, i would like the url to stop accepting oath/token as the authorizationserver, and accept tokens from the clientid mentioned. How do i go about this?

**Comment by Smedzlatko** [comment]
You can remove all the code dedicated to authorization server and specify only the clientDetails url (your Github auth server). That should do the trick.

**Comment by anotherrohit** [comment]
@Smedzlatko removed the entire OATH2Config class and put restTemplate in the client application as 	response = restTemplate.exchange(access_token_url, HttpMethod.POST, request, String.class), but running in to some issue. Do you have a similar client example

**Comment by Smedzlatko** [comment]
Hi, could you provide me with more details? I probably misunderstood your question. If you want to use this service as a resource server, you can link it to another auth server using the userInfo endpoint. If you have the access token from the auth server, you can then access any endpoint in the resource server (eq. `/people`) via REST with this token.

The token should be added to the request headers (`Authorization: Bearer <access_token>`)

**Comment by Smedzlatko** [comment]
Closing issue for lack of details. Re-open if needed.
