### ISSUE TITLE
invalid_client and NoSuchClientException

### ISSUE THREAD

**Issue by terziisk** [gigsterous/gigy-example#15]
Hi! I got your last version of master. And when i try to send this request "http://localhost:8000/gigy/oauth/token" through Postman with POST and Basic Auth (Username=peter@example.com, Password=password) i got the next error: 
> {
>     "error": "invalid_client",
>     "error_description": "Bad client credentials"
> }

In console i see:

> INFO 17336 --- [nio-8000-exec-4] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: NoSuchClientException, No client with requested id: peter@example.com

But in database the client exists. Besides that  loadUserByUsername - return correct user.
What can it be?

**Comment by Smedzlatko** [comment]
That's not how OAuth2 works. The token endpoint is secured via clientId and clientSecret (gigy:secret)
You need to provide these values in the basic auth header and the body (url encoded) of the request should contain the `grant_type` (in your case `password`), and the `username` (peter@example.com) and `password` (password).

See the example cUrl request in the readme.

**Comment by terziisk** [comment]
Thanks! Yes, this is what - what was missing. Added in Basic Auth  Username=gigy, Password=secret, and in x-www-form-urlencoded  body username, password and grant_type - and all done. Works fine!
