### ISSUE TITLE
An Authentication object was not found in the SecurityContext

### ISSUE THREAD

**Issue by VictorKozachek** [gigsterous/gigy-example#5]
Hi, 

How to fix it?

Thanks

**Comment by Smedzlatko** [comment]
Hi Victor,
Could you, please, provide more details abotu this exception and include stacktrace? I just tried everything out and was not able to replicate this error.

**Comment by VictorKozachek** [comment]
Hi, yes, I can,

I downloaded your code, built it and ran. Everything works just okay. I could call "token" method, received access_token value and then use it in order to call rest of methods.

I'm trying to integrate your code to my project. I can compile and run it without any problem. I can call "token" method and receive access_token value. But I receive exception "An Authentication object was not found in the SecurityContext" during calling rest of methods. It looks like it needs TokenStore or Filter, I'm not sure, I study Spring Boot and not a guru.

Thanks.

P.S. Sorry for my English.

**Comment by Smedzlatko** [comment]
So in short, the code in our example project is working fine and there are no issues with that. You have a problem with integrating the code into your personal project. Could you link your repository (if it is public) so I can take a look at your code? If not, there is not much I can do since I don't have enough details to debug your issue.

**Comment by VictorKozachek** [comment]
I've found problem. It was my fail. Sorry :( I did't integrate all code properly. Now it works.

Thanks.

**Comment by Smedzlatko** [comment]
I am glad this was solved.

**Comment by ezeev** [comment]
Hi @VictorKozachek - do you mind shedding light on what the problem was? I'm hitting the same error whilst trying to integrate @Smedzlatko's example into my own project.

**Comment by anil1712** [comment]
Hi @VictorKozachek @ezeev 
I am also getting the same exception while integrating with my project. 
Can you please explain to me how you resolved this issue?

Thanks
