### ISSUE TITLE
Question: How did you authenticate the password?

### ISSUE THREAD

**Issue by kenneth22** [gigsterous/gigy-example#6]

**Comment by Smedzlatko** [comment]
Hi, The `OAuth2Config` class is responsible for configuring athentication manager and user details. The credentials than come from the in-memory database.

Could you be more specific? I am more than happy to explain if you tell me what is unclear to you.

Cheers,
Martin

**Comment by JekRock** [comment]
Can you add an example with MySql or some else database with users roles? Or just show a difference in code.

**Comment by Smedzlatko** [comment]
The code for MySQL database would look exactly the same. The only difference would be `application.properties` which would contain different database endpoint and driver.

**Comment by JekRock** [comment]
@Smedzlatko Thanks! I'll try.

**Comment by JekRock** [comment]
@Smedzlatko I'm trying to use your code as example for my test project, but getting error 

> An Authentication object was not found in the SecurityContext
