### ISSUE TITLE
Can you provide how use refresh token in curl ?

### ISSUE THREAD

**Issue by M-Thirumal** [gigsterous/gigy-example#7]
Can you provide how use refresh token in curl ?

**Comment by Smedzlatko** [comment]
Hi,

Sorry for a late response. An example for refresh token would look something like this (it works with correct token - I tested it):

```
curl -i --user 'gigy:secret' \
-d 'grant_type=refresh_token&client_id=gigy&client_secret=secret&refresh_token=5ce4902a-e466-452d-8bbb-0fb1bf378f8a' \
-X POST http://localhost:8000/gigy/oauth/token
```

**Comment by madhanan** [comment]
How to get the refresh token. 
In my Curl output i don't get a refresh token.

What could be the issue ?

`curl -X POST https://login.microsoftonline.com/12345/oauth2/token ^
-F grant_type=client_credentials ^
-F resource=https://management.core.windows.net/ ^
-F client_id=12345-abcde ^
-F client_secret=12345abcde`

Output - 
 
{
	"token_type": "Bearer",
	"expires_in": "3600",
	"ext_expires_in": "3600",
	"expires_on": "1554368330",
	"not_before": "1554364430",
	"resource": "https://management.core.windows.net/",
	"access_token": "XXXXXXXXXXXXX"
}
