### ISSUE TITLE
coma is not allowed there?

### ISSUE THREAD

**Issue by dimmonn** [gigsterous/gigy-example#8]
https://github.com/gigsterous/gigy-example/blob/2255e787e4af145a3588dbc396e610f439e6ba82/src/main/resources/schema.sql#L6

**Comment by Smedzlatko** [comment]
Hi,

I don't thing it matters but you are right that it would be a good practice to be consistent and remove these unnecessary comas from the code.

Cheers,
Martin

**Comment by dimmonn** [comment]
thanks mate


when the coma is present i got sql related exeptions


03 октября 2017, 11:35:59, от Martin Myslík <notifications@github.com>: 


Hi,

I don't thing it matters but you are right that it would be a good practice to be consistent and remove these unnecessary comas from the code.

Cheers,
Martin

**Comment by Smedzlatko** [comment]
Strangely, it works for me. I will fix it later when I get to it. You are welcome to create a PR with a fix if you want :)

**Comment by antrix190** [comment]
Hey @Smedzlatko @dimmonn I changed the schema.sql file as discussed in this issue. Please review and approve.

**Comment by Smedzlatko** [comment]
Hi @antrix190 Thanks for the contribution. I merged your PR.
