### ISSUE TITLE
curl in readme doesn't work

### ISSUE THREAD

**Issue by dimmonn** [gigsterous/gigy-example#9]
2017-09-20 23:20:07.867  INFO 18452 --- [nio-8080-exec-5] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: NoSuchClientException, No client with requested id: peter

**Comment by Smedzlatko** [comment]
Hi,

Sorry for the late response. I just tested the code and the curl command as well and it works for me. After I run the application with `mvn spring-boot:run` adn use the cUrl command for token, I get the access token without any problem:

```
curl -X POST --user 'gigy:secret' -d 'grant_type=password&username=peter@example.com&password=password' http://localhost:8000/gigy/oauth/token
```

```
{"access_token":"5aa3ee70-b324-44fb-9e0d-2467a8adcfb8","token_type":"bearer","refresh_token":"5ce4902a-e466-452d-8bbb-0fb1bf378f8a","expires_in":3599,"scope":"read write"}
```

'Gigy' is the client id, not 'peter'. In my example, you need to use the client id and client secret (gigy:secret) and some existing user credentials - in this case, 'peter@example.com - password'. What seems to be the problem? Did you use the correct command?
